### ISSUE TITLE
UWP CornerRadius not working on Xamarin.Forms 4.8

### ISSUE THREAD

**Issue by craigwi** [sthewissen/Xamarin.Forms.PancakeView#150]
The current UWP sample in the master branch (using UAP -> 18362) results in colored backgrounds not getting clipped to border radius.  See attached as an example.

![image](https://user-images.githubusercontent.com/6687101/98471042-84b5fa00-219e-11eb-9cfb-30c70a09eb8c.png)

**Comment by gceaser** [comment]
Having the same issue.  Will this be updated soon?

**Comment by Tumeski** [comment]
Xamarin.Forms 4.8.0.1687 currently has this same.

**Comment by BillyMartin1964** [comment]
Well, it seems that the gradient obeys the border, so you can just do a gradient with start and endpoint the same:

```
     <pancakeView:PancakeView.BackgroundGradientStops StartPoint="0,0" EndPoint="0,0">
                <pancakeView:GradientStop Offset="0.1" Color="{StaticResource ScoreBoardBackgroundColor}" />
            </pancakeView:PancakeView.BackgroundGradientStops>
```

**Comment by nor0x** [comment]
this is still happening on Xamarin.Forms 5.0.0.1874

**Comment by Orgbrat** [comment]
Is this fixed in Xamarin.Forms.PancakeView v2.3.0.763-beta?

**Comment by craigwi** [comment]
No, I tried v2.3.0.763-beta and based on my tests this is not fixed.
